export const LANGUAGES: { code: string; name: string }[] = [
  { code: "auto", name: "Auto (browser)" },
  { code: "en-US", name: "English (United States)" },
  { code: "en-GB", name: "English (UK)" },
  { code: "hi-IN", name: "Hindi (India)" },
  { code: "bn-IN", name: "Bengali (India)" },
  { code: "mr-IN", name: "Marathi (India)" },
  { code: "ta-IN", name: "Tamil (India)" },
  { code: "te-IN", name: "Telugu (India)" },
  { code: "ur-PK", name: "Urdu (Pakistan)" },
  { code: "es-ES", name: "Spanish (Spain)" },
  { code: "es-MX", name: "Spanish (Mexico)" },
  { code: "fr-FR", name: "French (France)" },
  { code: "pt-BR", name: "Portuguese (Brazil)" },
  { code: "de-DE", name: "German (Germany)" },
  { code: "ru-RU", name: "Russian (Russia)" },
  { code: "ar-SA", name: "Arabic (Saudi Arabia)" },
  { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "ja-JP", name: "Japanese (Japan)" },
  { code: "ko-KR", name: "Korean (South Korea)" },
  { code: "id-ID", name: "Indonesian (Indonesia)" },
  { code: "vi-VN", name: "Vietnamese (Vietnam)" },
  { code: "th-TH", name: "Thai (Thailand)" },
  { code: "ms-MY", name: "Malay (Malaysia)" },
  { code: "tr-TR", name: "Turkish (Turkey)" },
  { code: "it-IT", name: "Italian (Italy)" },
  { code: "nl-NL", name: "Dutch (Netherlands)" },
  { code: "pl-PL", name: "Polish (Poland)" },
  { code: "sw-KE", name: "Swahili (Kenya)" },
];
